def try_me():
    print("try is successful")